apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: demo-micro
  labels:
    app: order-service
    service: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 9001
      targetPort: 9001
  type: ClusterIP
