apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: demo-micro
  labels:
    app: notification-service
    service: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 9002
      targetPort: 9002
  type: ClusterIP
