---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: demo-micro
type: Opaque
data:
  # postgres / postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: demo-micro
type: Opaque
data:
  # admin / root (base64 encoded)
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cm9vdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: demo-micro
type: Opaque
data:
  # pass (base64 encoded)
  REDIS_PASSWORD: cGFzcw==

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: demo-micro
type: Opaque
data:
  # test / test (base64 encoded)
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  AWS_SESSION_TOKEN: dGVzdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secret
  namespace: demo-micro
type: Opaque
data:
  # your_password (base64 encoded)
  ELASTIC_PASSWORD: eW91cl9wYXNzd29yZA==
