apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: demo-micro
  labels:
    app: inventory-service
    service: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
